keycloak_host: keycloak.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
kube_prometheus_stack_alertmanager_host: alertmanager.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
kube_prometheus_stack_grafana_host: grafana.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
kube_prometheus_stack_prometheus_host: prometheus.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_barbican_api_host: key-manager.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_cinder_api_host: volume.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_designate_api_host: dns.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_glance_api_host: image.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_heat_api_host: orchestration.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_heat_cfn_api_host: cloudformation.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_horizon_api_host: dashboard.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_ironic_api_host: baremetal.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_keystone_api_host: identity.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_magnum_api_host: container-infra.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_magnum_registry_host: container-infra-registry.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_manila_api_host: share.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_neutron_api_host: network.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_nova_api_host: compute.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_nova_novnc_host: vnc.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_octavia_api_host: load-balancer.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_placement_api_host: placement.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
openstack_helm_endpoints_region_name: RegionOne
openstack_helm_endpoints_rgw_host: object-store.{{ hostvars['ctl1']['ansible_host'].replace('.', '-') }}.nip.io
