keycloak_host: keycloak.192-168-33-254.nip.io
kube_prometheus_stack_alertmanager_host: alertmanager.192-168-33-254.nip.io
kube_prometheus_stack_grafana_host: grafana.192-168-33-254.nip.io
kube_prometheus_stack_prometheus_host: prometheus.192-168-33-254.nip.io
openstack_helm_endpoints_barbican_api_host: key-manager.192-168-33-254.nip.io
openstack_helm_endpoints_cinder_api_host: volume.192-168-33-254.nip.io
openstack_helm_endpoints_designate_api_host: dns.192-168-33-254.nip.io
openstack_helm_endpoints_glance_api_host: image.192-168-33-254.nip.io
openstack_helm_endpoints_heat_api_host: orchestration.192-168-33-254.nip.io
openstack_helm_endpoints_heat_cfn_api_host: cloudformation.192-168-33-254.nip.io
openstack_helm_endpoints_horizon_api_host: dashboard.192-168-33-254.nip.io
openstack_helm_endpoints_ironic_api_host: baremetal.192-168-33-254.nip.io
openstack_helm_endpoints_keystone_api_host: identity.192-168-33-254.nip.io
openstack_helm_endpoints_magnum_api_host: container-infra.192-168-33-254.nip.io
openstack_helm_endpoints_magnum_registry_host: container-infra-registry.192-168-33-254.nip.io
openstack_helm_endpoints_manila_api_host: share.192-168-33-254.nip.io
openstack_helm_endpoints_neutron_api_host: network.192-168-33-254.nip.io
openstack_helm_endpoints_nova_api_host: compute.192-168-33-254.nip.io
openstack_helm_endpoints_nova_novnc_host: vnc.192-168-33-254.nip.io
openstack_helm_endpoints_octavia_api_host: load-balancer.192-168-33-254.nip.io
openstack_helm_endpoints_placement_api_host: placement.192-168-33-254.nip.io
openstack_helm_endpoints_region_name: RegionOne
openstack_helm_endpoints_rgw_host: object-store.192-168-33-254.nip.io
