keycloak_host: 192.168.33.254
kube_prometheus_stack_alertmanager_host: 192.168.33.254
kube_prometheus_stack_grafana_host: 192.168.33.254
kube_prometheus_stack_prometheus_host: 192.168.33.254
openstack_helm_endpoints_barbican_api_host: 192.168.33.254
openstack_helm_endpoints_cinder_api_host: 192.168.33.254
openstack_helm_endpoints_designate_api_host: 192.168.33.254
openstack_helm_endpoints_glance_api_host: 192.168.33.254
openstack_helm_endpoints_heat_api_host: 192.168.33.254
openstack_helm_endpoints_heat_cfn_api_host: 192.168.33.254
openstack_helm_endpoints_horizon_api_host: 192.168.33.254
openstack_helm_endpoints_ironic_api_host: 192.168.33.254
openstack_helm_endpoints_keystone_api_host: 192.168.33.254
openstack_helm_endpoints_magnum_api_host: 192.168.33.254
openstack_helm_endpoints_magnum_registry_host: 192.168.33.254
openstack_helm_endpoints_manila_api_host: 192.168.33.254
openstack_helm_endpoints_neutron_api_host: 192.168.33.254
openstack_helm_endpoints_nova_api_host: 192.168.33.254
openstack_helm_endpoints_nova_novnc_host: 192.168.33.254
openstack_helm_endpoints_octavia_api_host: 192.168.33.254
openstack_helm_endpoints_placement_api_host: 192.168.33.254
openstack_helm_endpoints_region_name: 192.168.33.254
openstack_helm_endpoints_rgw_host: 192.168.33.254
