keycloak_host: keycloak.t1.a8e.ricolky.com
kube_prometheus_stack_alertmanager_host: alertmanager.t1.a8e.ricolky.com
kube_prometheus_stack_grafana_host: grafana.t1.a8e.ricolky.com
kube_prometheus_stack_prometheus_host: prometheus.t1.a8e.ricolky.com
openstack_helm_endpoints_barbican_api_host: key-manager.t1.a8e.ricolky.com
openstack_helm_endpoints_cinder_api_host: volume.t1.a8e.ricolky.com
openstack_helm_endpoints_designate_api_host: dns.t1.a8e.ricolky.com
openstack_helm_endpoints_glance_api_host: image.t1.a8e.ricolky.com
openstack_helm_endpoints_heat_api_host: orchestration.t1.a8e.ricolky.com
openstack_helm_endpoints_heat_cfn_api_host: cloudformation.t1.a8e.ricolky.com
openstack_helm_endpoints_horizon_api_host: dashboard.t1.a8e.ricolky.com
openstack_helm_endpoints_ironic_api_host: baremetal.t1.a8e.ricolky.com
openstack_helm_endpoints_keystone_api_host: identity.t1.a8e.ricolky.com
openstack_helm_endpoints_magnum_api_host: container-infra.t1.a8e.ricolky.com
openstack_helm_endpoints_magnum_registry_host: container-infra-registry.t1.a8e.ricolky.com
openstack_helm_endpoints_manila_api_host: share.t1.a8e.ricolky.com
openstack_helm_endpoints_neutron_api_host: network.t1.a8e.ricolky.com
openstack_helm_endpoints_nova_api_host: compute.t1.a8e.ricolky.com
openstack_helm_endpoints_nova_novnc_host: vnc.t1.a8e.ricolky.com
openstack_helm_endpoints_octavia_api_host: load-balancer.t1.a8e.ricolky.com
openstack_helm_endpoints_placement_api_host: placement.t1.a8e.ricolky.com
openstack_helm_endpoints_region_name: RegionOne
openstack_helm_endpoints_rgw_host: object-store.t1.a8e.ricolky.com
