keycloak_host: keycloak.38-108-68-238.nip.io
kube_prometheus_stack_alertmanager_host: alertmanager.38-108-68-238.nip.io
kube_prometheus_stack_grafana_host: grafana.38-108-68-238.nip.io
kube_prometheus_stack_prometheus_host: prometheus.38-108-68-238.nip.io
openstack_helm_endpoints_barbican_api_host: key-manager.38-108-68-238.nip.io
openstack_helm_endpoints_cinder_api_host: volume.38-108-68-238.nip.io
openstack_helm_endpoints_designate_api_host: dns.38-108-68-238.nip.io
openstack_helm_endpoints_glance_api_host: image.38-108-68-238.nip.io
openstack_helm_endpoints_heat_api_host: orchestration.38-108-68-238.nip.io
openstack_helm_endpoints_heat_cfn_api_host: cloudformation.38-108-68-238.nip.io
openstack_helm_endpoints_horizon_api_host: dashboard.38-108-68-238.nip.io
openstack_helm_endpoints_ironic_api_host: baremetal.38-108-68-238.nip.io
openstack_helm_endpoints_keystone_api_host: identity.38-108-68-238.nip.io
openstack_helm_endpoints_magnum_api_host: container-infra.38-108-68-238.nip.io
openstack_helm_endpoints_magnum_registry_host: container-infra-registry.38-108-68-238.nip.io
openstack_helm_endpoints_manila_api_host: share.38-108-68-238.nip.io
openstack_helm_endpoints_neutron_api_host: network.38-108-68-238.nip.io
openstack_helm_endpoints_nova_api_host: compute.38-108-68-238.nip.io
openstack_helm_endpoints_nova_novnc_host: vnc.38-108-68-238.nip.io
openstack_helm_endpoints_octavia_api_host: load-balancer.38-108-68-238.nip.io
openstack_helm_endpoints_placement_api_host: placement.38-108-68-238.nip.io
openstack_helm_endpoints_region_name: RegionOne
openstack_helm_endpoints_rgw_host: object-store.38-108-68-238.nip.io
