---
neutron_helm_values:
  conf:
    auto_bridge_add:
      br-ex: ens4

neutron_networks:
- external: true
  mtu_size: 1500
  name: public
  port_security_enabled: true
  provider_network_type: flat
  provider_physical_network: external
  shared: true
  subnets:
  - allocation_pool_end: 192.168.44.220
    allocation_pool_start: 192.168.44.200
    cidr: 192.168.44.0/24
    enable_dhcp: true
    gateway_ip: 192.168.44.10
    name: public-subnet

