powerstore_password: secrete123
ldap_password: secrete123
atmosphere_object_storage_service_user_password: secrete123
barbican_kek: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
keycloak_admin_password: secrete123
keycloak_database_password: secrete123
grafana_keycloak_client_secret: secrete123
keystone_keycloak_client_secret: secrete123
keystone_oidc_crypto_passphrase: secrete123
openstack_helm_endpoints_barbican_keystone_password: secrete123
openstack_helm_endpoints_barbican_mariadb_password: secrete123
openstack_helm_endpoints_cinder_keystone_password: secrete123
openstack_helm_endpoints_cinder_mariadb_password: secrete123
openstack_helm_endpoints_cinder_rabbitmq_password: secrete123
openstack_helm_endpoints_designate_keystone_password: secrete123
openstack_helm_endpoints_designate_mariadb_password: secrete123
openstack_helm_endpoints_designate_rabbitmq_password: secrete123
openstack_helm_endpoints_glance_keystone_password: secrete123
openstack_helm_endpoints_glance_mariadb_password: secrete123
openstack_helm_endpoints_glance_rabbitmq_password: secrete123
openstack_helm_endpoints_heat_keystone_password: secrete123
openstack_helm_endpoints_heat_mariadb_password: secrete123
openstack_helm_endpoints_heat_rabbitmq_password: secrete123
openstack_helm_endpoints_heat_stack_user_keystone_password: secrete123
openstack_helm_endpoints_heat_trustee_keystone_password: secrete123
openstack_helm_endpoints_horizon_mariadb_password: secrete123
openstack_helm_endpoints_ironic_keystone_password: secrete123
openstack_helm_endpoints_ironic_mariadb_password: secrete123
openstack_helm_endpoints_ironic_rabbitmq_password: secrete123
openstack_helm_endpoints_keystone_admin_password: secrete123
openstack_helm_endpoints_keystone_mariadb_password: secrete123
openstack_helm_endpoints_keystone_rabbitmq_password: secrete123
openstack_helm_endpoints_memcached_secret_key: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
openstack_helm_endpoints_magnum_keystone_password: secrete123
openstack_helm_endpoints_magnum_mariadb_password: secrete123
openstack_helm_endpoints_magnum_rabbitmq_password: secrete123
openstack_helm_endpoints_neutron_keystone_password: secrete123
openstack_helm_endpoints_neutron_mariadb_password: secrete123
openstack_helm_endpoints_neutron_metadata_secret: secrete123
openstack_helm_endpoints_neutron_rabbitmq_password: secrete123
openstack_helm_endpoints_nova_keystone_password: secrete123
openstack_helm_endpoints_nova_mariadb_password: secrete123
openstack_helm_endpoints_nova_rabbitmq_password: secrete123
openstack_helm_endpoints_octavia_keystone_password: secrete123
openstack_helm_endpoints_octavia_mariadb_password: secrete123
openstack_helm_endpoints_octavia_rabbitmq_password: secrete123
openstack_helm_endpoints_placement_keystone_password: secrete123
openstack_helm_endpoints_placement_mariadb_password: secrete123
openstack_helm_endpoints_rabbitmq_admin_password: secrete123
openstack_helm_endpoints_senlin_keystone_password: secrete123
openstack_helm_endpoints_senlin_mariadb_password: secrete123
openstack_helm_endpoints_senlin_rabbitmq_password: secrete123
openstack_helm_endpoints_manila_keystone_password: secrete123
openstack_helm_endpoints_manila_mariadb_password: secrete123
openstack_helm_endpoints_manila_rabbitmq_password: secrete123
openstack_helm_endpoints_tempest_keystone_password: secrete123
openstack_helm_endpoints_openstack_exporter_keystone_password: secrete123
heat_auth_encryption_key: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
octavia_heartbeat_key: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
kube_prometheus_stack_grafana_admin_password: secrete123

