powerstore_password: secrete123
ldap_password: secrete123
atmosphere_object_storage_service_user_password: secrete123
barbican_kek: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
keycloak_admin_password: secrete123
keycloak_database_password: secrete123
grafana_keycloak_client_secret: secrete123
keystone_keycloak_client_secret: secrete123
keystone_oidc_crypto_passphrase: secrete123
openstack_helm_endpoints_barbican_keystone_password: secrete123
openstack_helm_endpoints_barbican_mariadb_password: secrete123
openstack_helm_endpoints_cinder_keystone_password: secrete123
openstack_helm_endpoints_cinder_mariadb_password: secrete123
openstack_helm_endpoints_cinder_rabbitmq_password: secrete123
openstack_helm_endpoints_designate_keystone_password: secrete123
openstack_helm_endpoints_designate_mariadb_password: secrete123
openstack_helm_endpoints_designate_rabbitmq_password: secrete123
openstack_helm_endpoints_glance_keystone_password: secrete123
openstack_helm_endpoints_glance_mariadb_password: secrete123
openstack_helm_endpoints_glance_rabbitmq_password: secrete123
openstack_helm_endpoints_heat_keystone_password: secrete123
openstack_helm_endpoints_heat_mariadb_password: secrete123
openstack_helm_endpoints_heat_rabbitmq_password: secrete123
openstack_helm_endpoints_heat_stack_user_keystone_password: secrete123
openstack_helm_endpoints_heat_trustee_keystone_password: secrete123
openstack_helm_endpoints_horizon_mariadb_password: secrete123
openstack_helm_endpoints_ironic_keystone_password: secrete123
openstack_helm_endpoints_ironic_mariadb_password: secrete123
openstack_helm_endpoints_ironic_rabbitmq_password: secrete123
openstack_helm_endpoints_keystone_admin_password: secrete123
openstack_helm_endpoints_keystone_mariadb_password: secrete123
openstack_helm_endpoints_keystone_rabbitmq_password: secrete123
openstack_helm_endpoints_memcached_secret_key: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
openstack_helm_endpoints_magnum_keystone_password: secrete123
openstack_helm_endpoints_magnum_mariadb_password: secrete123
openstack_helm_endpoints_magnum_rabbitmq_password: secrete123
openstack_helm_endpoints_neutron_keystone_password: secrete123
openstack_helm_endpoints_neutron_mariadb_password: secrete123
openstack_helm_endpoints_neutron_metadata_secret: secrete123
openstack_helm_endpoints_neutron_rabbitmq_password: secrete123
openstack_helm_endpoints_nova_keystone_password: secrete123
openstack_helm_endpoints_nova_mariadb_password: secrete123
openstack_helm_endpoints_nova_rabbitmq_password: secrete123
openstack_helm_endpoints_octavia_keystone_password: secrete123
openstack_helm_endpoints_octavia_mariadb_password: secrete123
openstack_helm_endpoints_octavia_rabbitmq_password: secrete123
openstack_helm_endpoints_placement_keystone_password: secrete123
openstack_helm_endpoints_placement_mariadb_password: secrete123
openstack_helm_endpoints_rabbitmq_admin_password: secrete123
openstack_helm_endpoints_senlin_keystone_password: secrete123
openstack_helm_endpoints_senlin_mariadb_password: secrete123
openstack_helm_endpoints_senlin_rabbitmq_password: secrete123
openstack_helm_endpoints_manila_keystone_password: secrete123
openstack_helm_endpoints_manila_mariadb_password: secrete123
openstack_helm_endpoints_manila_rabbitmq_password: secrete123
openstack_helm_endpoints_tempest_keystone_password: secrete123
openstack_helm_endpoints_openstack_exporter_keystone_password: secrete123
heat_auth_encryption_key: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
octavia_heartbeat_key: FJtPTOCpIYydAjRz1vd91pZn9a1lpQ8q5WyNy80SpSg=
kube_prometheus_stack_grafana_admin_password: secrete123
keepalived_password: secrete123
openstack_helm_endpoints_rgw_keystone_password: secrete123
openstack_helm_endpoints_staffeln_mariadb_password: secrete123
manila_ssh_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAuBw1t+S5Q5TNASOFilEeAQ1HpV5iEkzOrIyCy059vyVWtzfNu7A8
  RYuTKvFI0w4437z49w+634SzZqMBfLtym6A9ijpmLGWyiIGegIAQTF86BdqPBYleBlQ/79
  h/6SuLhwZ1oCeGyFjG6EPT5QdsskU026lnn4Khvyi5v3FZ9s6Sh6hbXFyMIXKfk5dXA2Fn
  vtnn7Iy0gzmmQtMi6ovme9amQ+cTBb1X76Uh6T7DhoP+BioynHANYOk8VrMDlPF1evJbcZ
  MAsmp0drcD3Y2o3pzzZR8wxK2xmbRQDx1flmvdq1knPPYFAmqMwbwUqOE90VYRq0naDM1O
  AbqAfc1KxdTAQ85b1D/wgiZh+tTKEqhUdGPkrTzunCEKxhwZwwIHXrXqGcPT0aT8r/Vyry
  ulkSnHGpBvBe/v/zCjq8hWvmHEVQ+y3s2tQzEz0uipWz2ZfC4gwXjvq1wVRb7gWPhdLq7z
  boekcpT99b01IBDib6P6aA4nVKLgRF5vl9GDC6mlAAAFgCvp0Kor6dCqAAAAB3NzaC1yc2
  EAAAGBALgcNbfkuUOUzQEjhYpRHgENR6VeYhJMzqyMgstOfb8lVrc3zbuwPEWLkyrxSNMO
  ON+8+PcPut+Es2ajAXy7cpugPYo6ZixlsoiBnoCAEExfOgXajwWJXgZUP+/Yf+kri4cGda
  AnhshYxuhD0+UHbLJFNNupZ5+Cob8oub9xWfbOkoeoW1xcjCFyn5OXVwNhZ77Z5+yMtIM5
  pkLTIuqL5nvWpkPnEwW9V++lIek+w4aD/gYqMpxwDWDpPFazA5TxdXryW3GTALJqdHa3A9
  2NqN6c82UfMMStsZm0UA8dX5Zr3atZJzz2BQJqjMG8FKjhPdFWEatJ2gzNTgG6gH3NSsXU
  wEPOW9Q/8IImYfrUyhKoVHRj5K087pwhCsYcGcMCB1616hnD09Gk/K/1cq8rpZEpxxqQbw
  Xv7/8wo6vIVr5hxFUPst7NrUMxM9LoqVs9mXwuIMF476tcFUW+4Fj4XS6u826HpHKU/fW9
  NSAQ4m+j+mgOJ1Si4EReb5fRgwuppQAAAAMBAAEAAAGAIMltS5Vg5McgBv7jbjFp7XgG9U
  0sm+Ovvoy7UidlP2AP5Er8yVrmMOBdUf1sIaHbwQRvNdhISDvikvmeby8Wht5vdylVPrzR
  oXur1Wh4/pDKzXYRmEPRScFBLZ5ZkRWfIGmnEuFXIGCm83/4wUWkNs8aTbAKcx6ZXWiMQ6
  qVAd3hvGTf+D/G+MHn5ynBZim3hwZZRgf8sY3XrPjas/g8EHu2WktRWOlSOqwmsNnrig4B
  c+mZ38AYsdR3WV1B2wlwvCRCIrTFyKHgkON3V0pmPcsaeWQEEL2ZKJPrpitYEUDSh1vYEC
  8UN6B43fW1V3Pq6sdLoaitM32fEDgi56rNOc+5GNvqF7asvKinpSYjTGcJvjAw5yegfpMF
  3QhOanZ/jC3HX7j/IEu7I36U/LLCK0l1NsJLCd+jqGcBIL3zlF1BwPRzQ3XVM7XvPwnuU1
  lFM3s2tEsDUa97MXXHReDxANrkIAJlforuW8nOvseUmlTv3lCEYUaKfxtt/6LmStphAAAA
  wDNowiqJIvq/cPJH7lOCHz4whKU8vKcyNXPor20pNpgTVXQq6Nog0g9FYr2m1AXz1DINRy
  xk7GEy06gNDb9HtyiFmaXHJ/CQqu09vzyo2U0LRKLsXNQhjj6uPrXZeb7YDsfvRHWsQWTz
  XY+sGy4Sg939BVUAzPSbMXqbz53RyQeUXy/K1+LdxlFl6m+11P3e86Ce6l+7IRXyK53z11
  dMtzSwS+4tVvwlMHXjGvZsin8CNSkkNqhMELCN6f5zcCWcXgAAAMEA2aJEfOKUqYu9Lw7G
  UWw13vdktSXYrnb5kTm5luwfLDHwZZogN2pLM2E7hQTEYma40fAg+mW2mHLMBhNegK3/Pi
  pnhw5aItUtzpo0Ai25KtGv5qSHofWkXQGe2ZTZn8Nn3i+neCE4F87k1P5lzShVd/BFiaXH
  WdrJB+rHlKri+BeB2kaMqG3AkJJcJ+HXaZjQ7XLhYHiIsKrCVbh/SqCPPHhspHLSvmk3oF
  AouBtsgyDy7d9+vQCwHuPuY6aNET7NAAAAwQDYkQhCpanLPaq9B3Q2ydSPWvk2pHJesYL4
  HSQT+Qy5QmucxmNjW4EoZ7xE4pWKpV8wWhCE7WBGmgS9RCOBrh1Blcu6bLi5c0LnBQ4avn
  BJror+qzmzHHstsfrOMFt5L8uCmeE1Vdywq7Su/fib6knNYfFXMf236ZmjwL+PDWOUb6JD
  jLbfr8Y7+P68AA5jzP/nffrYAOpPGhCbuv7RZ1Y7IFQ7aBKAERUV4KH3S4YoUOHPUwhzmL
  efdYXwsunrZjkAAAAIcmljb0BkZXYBAgM=
  -----END OPENSSH PRIVATE KEY-----
nova_ssh_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAuBw1t+S5Q5TNASOFilEeAQ1HpV5iEkzOrIyCy059vyVWtzfNu7A8
  RYuTKvFI0w4437z49w+634SzZqMBfLtym6A9ijpmLGWyiIGegIAQTF86BdqPBYleBlQ/79
  h/6SuLhwZ1oCeGyFjG6EPT5QdsskU026lnn4Khvyi5v3FZ9s6Sh6hbXFyMIXKfk5dXA2Fn
  vtnn7Iy0gzmmQtMi6ovme9amQ+cTBb1X76Uh6T7DhoP+BioynHANYOk8VrMDlPF1evJbcZ
  MAsmp0drcD3Y2o3pzzZR8wxK2xmbRQDx1flmvdq1knPPYFAmqMwbwUqOE90VYRq0naDM1O
  AbqAfc1KxdTAQ85b1D/wgiZh+tTKEqhUdGPkrTzunCEKxhwZwwIHXrXqGcPT0aT8r/Vyry
  ulkSnHGpBvBe/v/zCjq8hWvmHEVQ+y3s2tQzEz0uipWz2ZfC4gwXjvq1wVRb7gWPhdLq7z
  boekcpT99b01IBDib6P6aA4nVKLgRF5vl9GDC6mlAAAFgCvp0Kor6dCqAAAAB3NzaC1yc2
  EAAAGBALgcNbfkuUOUzQEjhYpRHgENR6VeYhJMzqyMgstOfb8lVrc3zbuwPEWLkyrxSNMO
  ON+8+PcPut+Es2ajAXy7cpugPYo6ZixlsoiBnoCAEExfOgXajwWJXgZUP+/Yf+kri4cGda
  AnhshYxuhD0+UHbLJFNNupZ5+Cob8oub9xWfbOkoeoW1xcjCFyn5OXVwNhZ77Z5+yMtIM5
  pkLTIuqL5nvWpkPnEwW9V++lIek+w4aD/gYqMpxwDWDpPFazA5TxdXryW3GTALJqdHa3A9
  2NqN6c82UfMMStsZm0UA8dX5Zr3atZJzz2BQJqjMG8FKjhPdFWEatJ2gzNTgG6gH3NSsXU
  wEPOW9Q/8IImYfrUyhKoVHRj5K087pwhCsYcGcMCB1616hnD09Gk/K/1cq8rpZEpxxqQbw
  Xv7/8wo6vIVr5hxFUPst7NrUMxM9LoqVs9mXwuIMF476tcFUW+4Fj4XS6u826HpHKU/fW9
  NSAQ4m+j+mgOJ1Si4EReb5fRgwuppQAAAAMBAAEAAAGAIMltS5Vg5McgBv7jbjFp7XgG9U
  0sm+Ovvoy7UidlP2AP5Er8yVrmMOBdUf1sIaHbwQRvNdhISDvikvmeby8Wht5vdylVPrzR
  oXur1Wh4/pDKzXYRmEPRScFBLZ5ZkRWfIGmnEuFXIGCm83/4wUWkNs8aTbAKcx6ZXWiMQ6
  qVAd3hvGTf+D/G+MHn5ynBZim3hwZZRgf8sY3XrPjas/g8EHu2WktRWOlSOqwmsNnrig4B
  c+mZ38AYsdR3WV1B2wlwvCRCIrTFyKHgkON3V0pmPcsaeWQEEL2ZKJPrpitYEUDSh1vYEC
  8UN6B43fW1V3Pq6sdLoaitM32fEDgi56rNOc+5GNvqF7asvKinpSYjTGcJvjAw5yegfpMF
  3QhOanZ/jC3HX7j/IEu7I36U/LLCK0l1NsJLCd+jqGcBIL3zlF1BwPRzQ3XVM7XvPwnuU1
  lFM3s2tEsDUa97MXXHReDxANrkIAJlforuW8nOvseUmlTv3lCEYUaKfxtt/6LmStphAAAA
  wDNowiqJIvq/cPJH7lOCHz4whKU8vKcyNXPor20pNpgTVXQq6Nog0g9FYr2m1AXz1DINRy
  xk7GEy06gNDb9HtyiFmaXHJ/CQqu09vzyo2U0LRKLsXNQhjj6uPrXZeb7YDsfvRHWsQWTz
  XY+sGy4Sg939BVUAzPSbMXqbz53RyQeUXy/K1+LdxlFl6m+11P3e86Ce6l+7IRXyK53z11
  dMtzSwS+4tVvwlMHXjGvZsin8CNSkkNqhMELCN6f5zcCWcXgAAAMEA2aJEfOKUqYu9Lw7G
  UWw13vdktSXYrnb5kTm5luwfLDHwZZogN2pLM2E7hQTEYma40fAg+mW2mHLMBhNegK3/Pi
  pnhw5aItUtzpo0Ai25KtGv5qSHofWkXQGe2ZTZn8Nn3i+neCE4F87k1P5lzShVd/BFiaXH
  WdrJB+rHlKri+BeB2kaMqG3AkJJcJ+HXaZjQ7XLhYHiIsKrCVbh/SqCPPHhspHLSvmk3oF
  AouBtsgyDy7d9+vQCwHuPuY6aNET7NAAAAwQDYkQhCpanLPaq9B3Q2ydSPWvk2pHJesYL4
  HSQT+Qy5QmucxmNjW4EoZ7xE4pWKpV8wWhCE7WBGmgS9RCOBrh1Blcu6bLi5c0LnBQ4avn
  BJror+qzmzHHstsfrOMFt5L8uCmeE1Vdywq7Su/fib6knNYfFXMf236ZmjwL+PDWOUb6JD
  jLbfr8Y7+P68AA5jzP/nffrYAOpPGhCbuv7RZ1Y7IFQ7aBKAERUV4KH3S4YoUOHPUwhzmL
  efdYXwsunrZjkAAAAIcmljb0BkZXYBAgM=
  -----END OPENSSH PRIVATE KEY-----
