---
barbican_kek: OW15am1sWFRxbVF0T2tnMlJsOWVnVzNaRERXUjF6OGw=
heat_auth_encryption_key: lOFpuwqMdErM3wnR85wKlzZEDGRsyCww
keepalived_password: 6ykFEhVX0W74YBg8izuz42Hol94JL5io
keycloak_admin_password: 26gEiTrjXOfonbeGdZUv5g7kg1ldVA1Q
keycloak_database_password: SYQqcehZmH2TciwXKmMgHVHavwujYIvf
keystone_keycloak_client_secret: 46NBmiuJ0j2rgv9wkeco98mFXGagkVFB
keystone_oidc_crypto_passphrase: oNJyUcI5iMQi6aZbFc3ssj69ZXtmr9ZA
kube_prometheus_stack_grafana_admin_password: GoCtw4lr1LIv8ug1sHtyuRSeErZvDkgt
manila_ssh_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAuBw1t+S5Q5TNASOFilEeAQ1HpV5iEkzOrIyCy059vyVWtzfNu7A8
  RYuTKvFI0w4437z49w+634SzZqMBfLtym6A9ijpmLGWyiIGegIAQTF86BdqPBYleBlQ/79
  h/6SuLhwZ1oCeGyFjG6EPT5QdsskU026lnn4Khvyi5v3FZ9s6Sh6hbXFyMIXKfk5dXA2Fn
  vtnn7Iy0gzmmQtMi6ovme9amQ+cTBb1X76Uh6T7DhoP+BioynHANYOk8VrMDlPF1evJbcZ
  MAsmp0drcD3Y2o3pzzZR8wxK2xmbRQDx1flmvdq1knPPYFAmqMwbwUqOE90VYRq0naDM1O
  AbqAfc1KxdTAQ85b1D/wgiZh+tTKEqhUdGPkrTzunCEKxhwZwwIHXrXqGcPT0aT8r/Vyry
  ulkSnHGpBvBe/v/zCjq8hWvmHEVQ+y3s2tQzEz0uipWz2ZfC4gwXjvq1wVRb7gWPhdLq7z
  boekcpT99b01IBDib6P6aA4nVKLgRF5vl9GDC6mlAAAFgCvp0Kor6dCqAAAAB3NzaC1yc2
  EAAAGBALgcNbfkuUOUzQEjhYpRHgENR6VeYhJMzqyMgstOfb8lVrc3zbuwPEWLkyrxSNMO
  ON+8+PcPut+Es2ajAXy7cpugPYo6ZixlsoiBnoCAEExfOgXajwWJXgZUP+/Yf+kri4cGda
  AnhshYxuhD0+UHbLJFNNupZ5+Cob8oub9xWfbOkoeoW1xcjCFyn5OXVwNhZ77Z5+yMtIM5
  pkLTIuqL5nvWpkPnEwW9V++lIek+w4aD/gYqMpxwDWDpPFazA5TxdXryW3GTALJqdHa3A9
  2NqN6c82UfMMStsZm0UA8dX5Zr3atZJzz2BQJqjMG8FKjhPdFWEatJ2gzNTgG6gH3NSsXU
  wEPOW9Q/8IImYfrUyhKoVHRj5K087pwhCsYcGcMCB1616hnD09Gk/K/1cq8rpZEpxxqQbw
  Xv7/8wo6vIVr5hxFUPst7NrUMxM9LoqVs9mXwuIMF476tcFUW+4Fj4XS6u826HpHKU/fW9
  NSAQ4m+j+mgOJ1Si4EReb5fRgwuppQAAAAMBAAEAAAGAIMltS5Vg5McgBv7jbjFp7XgG9U
  0sm+Ovvoy7UidlP2AP5Er8yVrmMOBdUf1sIaHbwQRvNdhISDvikvmeby8Wht5vdylVPrzR
  oXur1Wh4/pDKzXYRmEPRScFBLZ5ZkRWfIGmnEuFXIGCm83/4wUWkNs8aTbAKcx6ZXWiMQ6
  qVAd3hvGTf+D/G+MHn5ynBZim3hwZZRgf8sY3XrPjas/g8EHu2WktRWOlSOqwmsNnrig4B
  c+mZ38AYsdR3WV1B2wlwvCRCIrTFyKHgkON3V0pmPcsaeWQEEL2ZKJPrpitYEUDSh1vYEC
  8UN6B43fW1V3Pq6sdLoaitM32fEDgi56rNOc+5GNvqF7asvKinpSYjTGcJvjAw5yegfpMF
  3QhOanZ/jC3HX7j/IEu7I36U/LLCK0l1NsJLCd+jqGcBIL3zlF1BwPRzQ3XVM7XvPwnuU1
  lFM3s2tEsDUa97MXXHReDxANrkIAJlforuW8nOvseUmlTv3lCEYUaKfxtt/6LmStphAAAA
  wDNowiqJIvq/cPJH7lOCHz4whKU8vKcyNXPor20pNpgTVXQq6Nog0g9FYr2m1AXz1DINRy
  xk7GEy06gNDb9HtyiFmaXHJ/CQqu09vzyo2U0LRKLsXNQhjj6uPrXZeb7YDsfvRHWsQWTz
  XY+sGy4Sg939BVUAzPSbMXqbz53RyQeUXy/K1+LdxlFl6m+11P3e86Ce6l+7IRXyK53z11
  dMtzSwS+4tVvwlMHXjGvZsin8CNSkkNqhMELCN6f5zcCWcXgAAAMEA2aJEfOKUqYu9Lw7G
  UWw13vdktSXYrnb5kTm5luwfLDHwZZogN2pLM2E7hQTEYma40fAg+mW2mHLMBhNegK3/Pi
  pnhw5aItUtzpo0Ai25KtGv5qSHofWkXQGe2ZTZn8Nn3i+neCE4F87k1P5lzShVd/BFiaXH
  WdrJB+rHlKri+BeB2kaMqG3AkJJcJ+HXaZjQ7XLhYHiIsKrCVbh/SqCPPHhspHLSvmk3oF
  AouBtsgyDy7d9+vQCwHuPuY6aNET7NAAAAwQDYkQhCpanLPaq9B3Q2ydSPWvk2pHJesYL4
  HSQT+Qy5QmucxmNjW4EoZ7xE4pWKpV8wWhCE7WBGmgS9RCOBrh1Blcu6bLi5c0LnBQ4avn
  BJror+qzmzHHstsfrOMFt5L8uCmeE1Vdywq7Su/fib6knNYfFXMf236ZmjwL+PDWOUb6JD
  jLbfr8Y7+P68AA5jzP/nffrYAOpPGhCbuv7RZ1Y7IFQ7aBKAERUV4KH3S4YoUOHPUwhzmL
  efdYXwsunrZjkAAAAIcmljb0BkZXYBAgM=
  -----END OPENSSH PRIVATE KEY-----
nova_ssh_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAuBw1t+S5Q5TNASOFilEeAQ1HpV5iEkzOrIyCy059vyVWtzfNu7A8
  RYuTKvFI0w4437z49w+634SzZqMBfLtym6A9ijpmLGWyiIGegIAQTF86BdqPBYleBlQ/79
  h/6SuLhwZ1oCeGyFjG6EPT5QdsskU026lnn4Khvyi5v3FZ9s6Sh6hbXFyMIXKfk5dXA2Fn
  vtnn7Iy0gzmmQtMi6ovme9amQ+cTBb1X76Uh6T7DhoP+BioynHANYOk8VrMDlPF1evJbcZ
  MAsmp0drcD3Y2o3pzzZR8wxK2xmbRQDx1flmvdq1knPPYFAmqMwbwUqOE90VYRq0naDM1O
  AbqAfc1KxdTAQ85b1D/wgiZh+tTKEqhUdGPkrTzunCEKxhwZwwIHXrXqGcPT0aT8r/Vyry
  ulkSnHGpBvBe/v/zCjq8hWvmHEVQ+y3s2tQzEz0uipWz2ZfC4gwXjvq1wVRb7gWPhdLq7z
  boekcpT99b01IBDib6P6aA4nVKLgRF5vl9GDC6mlAAAFgCvp0Kor6dCqAAAAB3NzaC1yc2
  EAAAGBALgcNbfkuUOUzQEjhYpRHgENR6VeYhJMzqyMgstOfb8lVrc3zbuwPEWLkyrxSNMO
  ON+8+PcPut+Es2ajAXy7cpugPYo6ZixlsoiBnoCAEExfOgXajwWJXgZUP+/Yf+kri4cGda
  AnhshYxuhD0+UHbLJFNNupZ5+Cob8oub9xWfbOkoeoW1xcjCFyn5OXVwNhZ77Z5+yMtIM5
  pkLTIuqL5nvWpkPnEwW9V++lIek+w4aD/gYqMpxwDWDpPFazA5TxdXryW3GTALJqdHa3A9
  2NqN6c82UfMMStsZm0UA8dX5Zr3atZJzz2BQJqjMG8FKjhPdFWEatJ2gzNTgG6gH3NSsXU
  wEPOW9Q/8IImYfrUyhKoVHRj5K087pwhCsYcGcMCB1616hnD09Gk/K/1cq8rpZEpxxqQbw
  Xv7/8wo6vIVr5hxFUPst7NrUMxM9LoqVs9mXwuIMF476tcFUW+4Fj4XS6u826HpHKU/fW9
  NSAQ4m+j+mgOJ1Si4EReb5fRgwuppQAAAAMBAAEAAAGAIMltS5Vg5McgBv7jbjFp7XgG9U
  0sm+Ovvoy7UidlP2AP5Er8yVrmMOBdUf1sIaHbwQRvNdhISDvikvmeby8Wht5vdylVPrzR
  oXur1Wh4/pDKzXYRmEPRScFBLZ5ZkRWfIGmnEuFXIGCm83/4wUWkNs8aTbAKcx6ZXWiMQ6
  qVAd3hvGTf+D/G+MHn5ynBZim3hwZZRgf8sY3XrPjas/g8EHu2WktRWOlSOqwmsNnrig4B
  c+mZ38AYsdR3WV1B2wlwvCRCIrTFyKHgkON3V0pmPcsaeWQEEL2ZKJPrpitYEUDSh1vYEC
  8UN6B43fW1V3Pq6sdLoaitM32fEDgi56rNOc+5GNvqF7asvKinpSYjTGcJvjAw5yegfpMF
  3QhOanZ/jC3HX7j/IEu7I36U/LLCK0l1NsJLCd+jqGcBIL3zlF1BwPRzQ3XVM7XvPwnuU1
  lFM3s2tEsDUa97MXXHReDxANrkIAJlforuW8nOvseUmlTv3lCEYUaKfxtt/6LmStphAAAA
  wDNowiqJIvq/cPJH7lOCHz4whKU8vKcyNXPor20pNpgTVXQq6Nog0g9FYr2m1AXz1DINRy
  xk7GEy06gNDb9HtyiFmaXHJ/CQqu09vzyo2U0LRKLsXNQhjj6uPrXZeb7YDsfvRHWsQWTz
  XY+sGy4Sg939BVUAzPSbMXqbz53RyQeUXy/K1+LdxlFl6m+11P3e86Ce6l+7IRXyK53z11
  dMtzSwS+4tVvwlMHXjGvZsin8CNSkkNqhMELCN6f5zcCWcXgAAAMEA2aJEfOKUqYu9Lw7G
  UWw13vdktSXYrnb5kTm5luwfLDHwZZogN2pLM2E7hQTEYma40fAg+mW2mHLMBhNegK3/Pi
  pnhw5aItUtzpo0Ai25KtGv5qSHofWkXQGe2ZTZn8Nn3i+neCE4F87k1P5lzShVd/BFiaXH
  WdrJB+rHlKri+BeB2kaMqG3AkJJcJ+HXaZjQ7XLhYHiIsKrCVbh/SqCPPHhspHLSvmk3oF
  AouBtsgyDy7d9+vQCwHuPuY6aNET7NAAAAwQDYkQhCpanLPaq9B3Q2ydSPWvk2pHJesYL4
  HSQT+Qy5QmucxmNjW4EoZ7xE4pWKpV8wWhCE7WBGmgS9RCOBrh1Blcu6bLi5c0LnBQ4avn
  BJror+qzmzHHstsfrOMFt5L8uCmeE1Vdywq7Su/fib6knNYfFXMf236ZmjwL+PDWOUb6JD
  jLbfr8Y7+P68AA5jzP/nffrYAOpPGhCbuv7RZ1Y7IFQ7aBKAERUV4KH3S4YoUOHPUwhzmL
  efdYXwsunrZjkAAAAIcmljb0BkZXYBAgM=
  -----END OPENSSH PRIVATE KEY-----

octavia_heartbeat_key: r39Ev66MKkSWqXX3Ay8rM3R2Z9mr546s
openstack_helm_endpoints_barbican_keystone_password: a8D6jiYUqcM0fYN1lsJR1N2jeytMUqXr
openstack_helm_endpoints_barbican_mariadb_password: ETGekWw73i51vluyQguGtR4kYiSdv9pG
openstack_helm_endpoints_cinder_keystone_password: PNC4V3f67JWAbFaKZ6XiutCDSmkjDO0b
openstack_helm_endpoints_cinder_mariadb_password: 6E78bzwBgbCDpxUgoSvF8rAC5HqQ8FfP
openstack_helm_endpoints_cinder_rabbitmq_password: g1fS88gQNaXs8dDlaO4D3tRShnOhukFa
openstack_helm_endpoints_designate_keystone_password: LbNiHWNv1GEqu59TVC0QDvAt9mzZyCqM
openstack_helm_endpoints_designate_mariadb_password: 7KgBUlWgVoz8hV5xt38JRopWW0X5EV72
openstack_helm_endpoints_designate_rabbitmq_password: 9DaRnHzPEdWueBLLxuCoOo6cTcs1NF6r
openstack_helm_endpoints_glance_keystone_password: NLqEhCt8eSrb8Db82ow393k6rJRxRTGd
openstack_helm_endpoints_glance_mariadb_password: QW44o0Khwkal1nH7AEOBxsEtJuwHJIr1
openstack_helm_endpoints_glance_rabbitmq_password: nB43jar1aqs1urQV252j8MhHMSTJJuS9
openstack_helm_endpoints_heat_keystone_password: 1FJ2IQ4AM6S44K6ueI5blbDLpggd1x6H
openstack_helm_endpoints_heat_mariadb_password: vEejAeOsRKEtJWmV1XCnawlSICsNKvlB
openstack_helm_endpoints_heat_rabbitmq_password: 9RvkotKhfj4r7Hjv8EDCmRtFZiyY2j9G
openstack_helm_endpoints_heat_stack_user_keystone_password: 7ptjfGMjV87eqKhkmRwUx3lijgkQPycU
openstack_helm_endpoints_heat_trustee_keystone_password: 9d0veeShyJqfmTqWRvj49pC88mHGcKgk
openstack_helm_endpoints_horizon_mariadb_password: jl2LKJsce12lCS4RShtgSnLC1eGUK4YE
openstack_helm_endpoints_ironic_keystone_password: 4BofSEtJoN6btjiS5sJo39Hi8xCXTXcT
openstack_helm_endpoints_ironic_mariadb_password: JG7JXoHABUEFaoB0tRjZpXpkmHr74xV7
openstack_helm_endpoints_ironic_rabbitmq_password: qKboKuohd4hwnfPXhjz2pTtVE7dK22TF
openstack_helm_endpoints_keystone_admin_password: d4CHICIy0pH6n5X6YligrOABOQHVM8vD
openstack_helm_endpoints_keystone_mariadb_password: bQXZCMOn3X11f0mcDCRKZa9JxbdJwFbI
openstack_helm_endpoints_keystone_rabbitmq_password: F6LPZNcEFvo6fXgZfvnvyyqSarDqPGCG
openstack_helm_endpoints_magnum_keystone_password: BMsu5pZMvtC161UkfplcIzCgI4EMGLKo
openstack_helm_endpoints_magnum_mariadb_password: CxhSkqZkEpT7M5kvvc5Hx8lvpm9qRPbu
openstack_helm_endpoints_magnum_rabbitmq_password: 8AA2ZonhgMGoJPAB6xnAsLDusdoQVe6k
openstack_helm_endpoints_manila_keystone_password: n7P7dxT8o7sj9CapXxwx1y8lhQn7w9t5
openstack_helm_endpoints_manila_mariadb_password: gL47PP9bf9XqIUZ7z4irAK0XtDY2il7O
openstack_helm_endpoints_memcached_secret_key: R8btYaWNgj0DQkTHPXtFJtTIO3434jEQ
openstack_helm_endpoints_neutron_keystone_password: CGzVWGNG6dfi1AMlYvVOJqxKM5WQ6Z6g
openstack_helm_endpoints_neutron_mariadb_password: JPx9BDdboBPJHgb1liB0NAlGWMIn4SNY
openstack_helm_endpoints_neutron_metadata_secret: PVUW3WEXjyweDNFrOy7hntu7PtW0vQLn
openstack_helm_endpoints_neutron_rabbitmq_password: cKLRSG3tkSjtOKkDCuDBW4J7egUbMZ2j
openstack_helm_endpoints_nova_keystone_password: NbX8dFbdXGkdHmJdMNvZMVK1wu0lYS0I
openstack_helm_endpoints_nova_mariadb_password: 8cEjjLeBjN7Ikfl0C5YfBWR6GW7KzSiA
openstack_helm_endpoints_nova_rabbitmq_password: beGujgsWxHsfLiRWgYuJNzxYp3AIcAe7
openstack_helm_endpoints_octavia_keystone_password: dpd50uQzhMMU1FtXRTVhPW8aJZGgaU2O
openstack_helm_endpoints_octavia_mariadb_password: bZfByNDRSIuusZWqAQFM2DTQfQ4q6XzW
openstack_helm_endpoints_octavia_rabbitmq_password: 1UV1HR5JOtn3vowrhNdwviVEtuMrpFOe
openstack_helm_endpoints_openstack_exporter_keystone_password: ZdsYQCoqFefNt5OB24mFGzbaCTJQoBMq
openstack_helm_endpoints_placement_keystone_password: L427I2tD2QY9JwFNaE7Pds45ruSFyLFZ
openstack_helm_endpoints_placement_mariadb_password: EQIbBMscF0aZSC3DDvWdkkLH1mXQlIAF
openstack_helm_endpoints_rabbitmq_admin_password: OPWrvtgOQQ2VPaDlRHepUAc3rEn4QvPO
openstack_helm_endpoints_rgw_keystone_password: YXnSiOhiC3gjqJsLEfXjU26HZ1q9kVnA
openstack_helm_endpoints_staffeln_mariadb_password: ALwVNdiKOd3fWWBwAblYBgcScVMfeJQF
openstack_helm_endpoints_tempest_keystone_password: hhDtbQjDybRuW1vB2xhmwkYOs7GrUXpv
