keycloak_database_password: secrete123
keycloak_admin_password: secrete123
kube_prometheus_stack_grafana_admin_password: secrete123
openstack_helm_endpoints_memcached_secret_key: secrete123
openstack_helm_endpoints_keystone_admin_password: secrete123
openstack_helm_endpoints_keystone_mariadb_password: secrete123
openstack_helm_endpoints_keystone_rabbitmq_password: secrete123
keystone_keycloak_client_secret: secrete123
keystone_oidc_crypto_passphrase: secrete123
openstack_helm_endpoints_horizon_mariadb_password: secrete123
